### ISSUE TITLE
The Newest Job System

### ISSUE THREAD

**Issue by TarasMartynyuk** [OrderOfThePorcupine/ProjectPorcupine#113]
# Let's recall what was the plan
The replacement of current character control system is one of the most grandioze items in the milestone, and other contributors tried to cope with it multiple times. This discussion is the folow-up of those attempts :  #14 and #29. My suggestion is to go with [_Goal Based Agents_](https://gamedevelopment.tutsplus.com/tutorials/goal-oriented-action-planning-for-a-smarter-ai--cms-20793) system, the closest hit from previous ideas is the @yonner 's comments on #14 thread. I'll go into the most detail, as i need your feedback and help.
# Idea
Simply put, there are three elements : a **Goal** - something _to be done_ that affects the world state; an **Agent** - someone who knows how to perform actions depending on the world state, and the **Action** - the simplest task, which changes  the world state. _Our_ goal is to link this elements together
# Architecture
First, how do we represent goal, speaking more specifically? It is the second most relevant part of design. I suggest to go with the idea of nested goals , as @yonner proposed. Lets have different tiers for it:

- **Goal** - an abstraction for what needs to be done - this is top level - tier, and it is only one for sure. It is basically the container which holds more detailed tasks. It also denotes it's priority, while more specific tasks do not  need to know anything about it.
- **Job** - a container for Actions, which we can use to decompose general tasks to specific ones(see examples).I think it will also have prerequisites and effects, like actions, which will be bound together( for example 1st job in a goal will make possible 2nd job to be done)
- **Action** is a lowest level task for an agent. It has prerequisites which must be true to do it (some world state properties) , and effects which'll take place after it is performed (changes to world state). We'll define world state later).

Goal { place furniture at the spot(x,y) }
//must be able to assign theese to different agents, and inform them about the status
//now we are decomposed enough to be able to assign the goals

- Job { haul materials to spot }
    - Action { move to stockpile}
    - Action { pick materials}
    - Action { move to spot}
- Job { construct }

Goal { lower sleep need to 0 }

- Job { sleep }
    - Action {move(to bed)}
    - Action {sleep}

Now let's jump to the other end of the goal->agent pipeline : **Agent**:

**GAPAgent** {
-   all characters have an object of this class(either composite to gameobject or C# class);
-  has all performable actions stored(same objects, reset when finished);
-   provides info about world state(with respect to this object e.g {'has logs': true, 'is not injured' : true}
let's handle the more complex conditions in the actions itself, via methods;
-   has JobPlanner component which knows how to construct action sequence for a job;
-   when goal is finished, callbacks to GoalController;
-   Either has needs directly implemented, or gets them from character obj;

}

**Action** {
-   preconditions - list of world state properties that must hold;
-   effects - world state properties that will be changed after acrion is;

}

This way, the agent only knows how to do the Job, and has the set of tools for it - Actions(which will actually be some variable containing specific actions - subclasses of Action class or something like that - e.g CutWoodAction, SleepAction). But, it is shortsighted - you must explicitly give it the _lowest level job_, that is - the one that is directly decomposed; this is brought up in questions 1 and 2. The task of choosing the most suitable Job for each Agent is done beyond the scope of the class. It only informs of the successful job completion. Some cases that can interupt the Job must be handled outside the scope, as well.

_Note_: "providing world state" part is implemented in its own class that is able to compute all the properties for this particular agent and provide it to JobPlanner(component), which will construct the most efficient sequence of actions to do the Job.

Having handled(more or less) easier parts, let's look on the hard one: transporting the abstracted Goal to the Agents, in a form that they can handle. The genius that will do it is:

**GoalController** {

- storage for all pending goals;
- add new goals here;
- remembers which colonists are working on which goals:
    - upon goal completement(feedback from agents) supplies agents with new goals;
    - only most low-level jobs(as they are the only one that can be done by agents);
    - used for prioritizing(later);
- assignes goals to agents:
    - //the chhosing logic should be encapsulated in this class only, 
    - knows how to prioritize goals globally( firefighting is selected over sleeping etc);
    - knows how to prioritize agents (chars with high construction skills should be given furniture placing over others etc);
}

See  question 3... Some my brain-storm born ideas include : 
1. Ensuring quick reaction to tasks:
    - performing Job choosing irregularly, based on callbacks( job finished, job status changed(consider 
    situation - 1st priority job was impossible to do and thus ignored, bt suddenly all the prerequisites 
    became met);
    - looping across _all_ agents in update and store status info in agent objects. Found a change - 
    modify current job distribution; 
2. Personalized job selection:
    - separate datastructure (imagine a queue) for each character, which is modified every time we need 
    to modify it, and the task of picking the best  job for an agent becomes trivial;

_Note_ how do we balance person based(e.g needs fullfilment) and global (e.g firefighting) work priorities interaction? 
There are much more details to be discussed than those underneath, also the in-between architecture is still pretty much uncharted waters, but basically what we need to decide is wether this system with suggested enhansments will be able to hold all that we need.
# Questions/Problems

1. Can we represent every task with such definiton of Job?
2. Is it posiible to have only 1 tier for Jobs(directly decomposing to Actions), or do the Jobs need to have other Jobs in them? How would we handle that(add another class for that last level and define Job as container for other Jobs?)
3. THE **GoalController** implementation?

**Comment by BraedonWooding** [comment]
Goal based actor systems are efficient and are often used for base building games, now while I would say that stuff like sleep action will be covered under different systems (a proper need system handling stuff like the more tired you are the slower you move/the less alert you are and so on) but the actual sleeping would be a 'goal' rather.  

Modding is a huge component of our systems, we want to make sure that modders could add unique jobs built on top of other systems, which I can see being achieved from your planned system, and this completely plays into your first question/problem.

I'm however in perhaps a bit of disagreement over why `Goal` is not equivalent to `Job` since in all real `Goals` there will only be one job?  Unless perhaps I'm misunderstanding your examples because even your construction one places the act to construct within one job (which I think is the right way to do it), maybe perhaps a `Goal` represents a final verifiable state of the world, as in the job is complete when said tile is built, the pathway to that tile, where to pick up the objects are individual and different jobs and possibly could change (lets say the player blocks off a path halfway through a job) but the goal remains?

Such as imagine this, you ask to place a furnace on position (1, 2), the character generates a path to follow and produces a job to sit within the goal (for purely encapsulation niceness) that job is to walk along that path and pick up the item at said path (the closest being tile (3, 4)) and walk over to (1, 2) and place furnace.

However, a user places a wall which blocks the pathfinding, now in your system what would occur?  Would the goal be discarded and rebuilt, or would simply the job be discarded and be rebuilt while the goal remains the same, such that the goal doesn't have to be reassigned to someone since the goal hasn't changed just merely the encapsulated job.  So in this manner a Goal represents something useful and thus could easily exist otherwise I don't really see the need for encapsulation if it's going to be discarded and jobs representing the whole event.

I quite like the queue idea though also for prioritisation (I think most consensus from previous efforts has been a priority system like rimworld has, as in numbering)

**Comment by koosemose** [comment]
@BraedonWooding Note the "place furniture at position" goal, it has two jobs, haul and construct. 

Also theoretically goals could have multiple possible alternative jobs, for example, lower sleep goal could be achieved by either "sleep in bed" or "drink energy drink". Perhaps not the best example as I doubt we will have energy drinks, but I think it at least illustrates the idea of a goal being achievable by different jobs.

Additionally, the "place furniture at position" could arguably be handled by different jobs, one representing actually constructing it from scratch (as in the example in original post), another representing taking an uninstalled furniture and placing it down (while similar, and in fact implemented using almost the same code, it isn't quite, particularly with potential future additions, constructing  for example could lead to a variable result, different qualities and such, and installation at worst would be failure to install or damage to furniture)

@TarasMartynyuk Regarding the goal controller, I don't like the idea of personalized job queues for each crew, primarily because that can end up very messy and confusing, and would cause a need of so many interactions and communications at various points that there would be a lot of failure points. Though the idea of a crew being able to take a group of jobs (or in the parlance you've used, goals), such as "Build X pieces of wall at these locations", just so that Crew will, for example work on a section of wall, rather building in alternating areas (would also potentially allow it to be handled such that the component jobs end up as "Get resources for all these walls", and then the individual construct jobs, so a Crew can carry all they can for multiple jobs. 

Also, even though it may sound counterintuitive, we don't want the "GoalController" too smart, (this was an issue with some of the earlier designs discussed), and take too many decisions out of the players hands. For example, rather than just automatically looking and saying "X person is best builder, they should do all the building", I, as a player, should be able to set priorities to do differently (which may not always be a mistake, if, for example, the best builder is also the best cook, I might want to prefer higher quality cooking and accept the lower quality building.

On the side of needs interaction, the intention has always been that needs will be able to interrupt with an urgency. As a rough sketch, let's say 3 levels of urgency, low, medium and high. Low urgency gets placed on a character's personal job queue (another situation where a character being able to take multiple jobs... sorry goals... the change in terminology makes things a little confusing... will help) at the back, and they will finish everything first, a medium urgency might get placed after the current job, and high immediately interrupts the current job. The exact "What each urgency level does" isn't set in stone, just an approximation, it will depend partially on how exactly the job system works, it might be that low urgency not only goes to the back of the line, but gets ignored as long as the Crew can get new goals from GoalController (so a low urgency sleepy character would only sleep if they had absolutely nothing else to do), a medium might instead go to the end of the queue but not let others in front, and a high will either interrupt or go after current... I'd have to double check what the need levels are and refamiliarize myself with it before setting anything down to any degree of certainty.

**Comment by BraedonWooding** [comment]
@koosemose Yes but the action `construct` is under move in the example which is what I was referring to (I didn't want to presume it was a typo).  Also and yes the alternative jobs is exactly what I was referring to an abstraction of the job to represent the current choice not to represent the final choice.

And I agree with the job queue sentiment, the form you suggested I've also suggested in the past and I do agree that taking multiple jobs is key to not having annoying interactions (such as constantly going back and forth for materials).

**Comment by koosemose** [comment]
I didn't actually notice the construct action under move, just that their was a construct job.. I would guess they accidentally got misordered.

**Comment by kd7uiy** [comment]
Closing this as we now have a good path forward in progress.
