### ISSUE TITLE
Settings- Don't confirm if no changes made.

### ISSUE THREAD

**Issue by kd7uiy** [OrderOfThePorcupine/ProjectPorcupine#155]
When opening the settings and hitting cancel, without changing anything, I was asked if I wanted to exit without saving the changes. This shouldn't happen.

**Comment by BraedonWooding** [comment]
This is actually quite straightforward since every SettingElement already tracks if it has been changed which you can see [here](https://github.com/OrderOfThePorcupine/ProjectPorcupine/blob/20779fa8b5bf3bd5f4cb49bff39ada02ad81360c/Assets/Scripts/UI/InGameUI/SettingsMenu/BaseSettingsElement.cs#L26).

I'll draft something up next time I get the chance should be as simple as a for loop that just checks the condition 😄.
