### ISSUE TITLE
Localization: Do we really still want it as a separate repository?

### ISSUE THREAD

**Issue by kd7uiy** [OrderOfThePorcupine/ProjectPorcupine#164]
Localization once upon a time was moved to a separate repository because, well, reasons. I guess at the time it was being frequently and furiously updated, so it make a bit of sense to have it separated. The question I have is, do we still want that kind of separation, or should we pull it back in to the main repository?

**Comment by BraedonWooding** [comment]
Another reason I believe was so that we could update the localization repository and still not have to also update the client.

Not that this isn’t possible with them merged but it is easier to handle with them separated (especially since you can just download the full zip which is faster than having the batch download a bunch of text files)
