### ISSUE TITLE
Cheat Mode spawning objects doesn't work

### ISSUE THREAD

**Issue by BraedonWooding** [OrderOfThePorcupine/ProjectPorcupine#178]
You can place down a single stack (i.e. 50) but once you have placed that down any more stacks placed, spawn 0 elements; that is a stack with a 0 as it's number and it can't be used for building!

**Comment by koosemose** [comment]
Just to narrow down the source of the issue, whatever is responsible for this bug is from the recent resurgence, as I recently ran a build from before the resurgence, in which it works fine.

**Comment by BraedonWooding** [comment]
For me it breaks before the resurgence.

What sha/commit are you running it on that it works?

**Comment by BraedonWooding** [comment]
Actually it was from a commit a few commits ago (before regression).

Will supply patch now.  Basically the problem was that we cached Inventory so we didn't have to keep creating temporary copies for the visuals, but when we placed the inventory it invalided the inventory that we cached.  So in reality it was a pretty simple fix (single line to clone the inventory after placing it).

**Comment by BraedonWooding** [comment]
Fixed via #188

**Comment by koosemose** [comment]
Very peculiar, as the version I was running was the last prebuilt binary before resurgence... I wonder if there is something that caused it to only fail in editor... Or maybe it's due to unity version differences (though I don't see how that would work), since presumably you were testing an older commit (for an older version of unity) in the version of unity PP is currently built for...

Moot points all of them, if you've got a working fix... just a peculiarity.
