### ISSUE TITLE
Extend/Replace Localization code

### ISSUE THREAD

**Issue by Kjarrigan** [OrderOfThePorcupine/ProjectPorcupine#82]
Extracted from #80 :

The later you start the worse it gets.... e.g. Quests is hardcoded in the data and Inventory has "too many" keys. The projects I localize work with a yaml-styled language file (the ruby-lib is called i18n). So you dont have key-value pairs but a whole tree structure. So it would look something like:

```
en:
  Inventory:
    raw_iron:
      name: "Iron Ore"
      description: "Raw Iron Ore, it needs to be processed before it's useful."
  Quest:
    "Mining Drone Beta Test Program":
      Name: "Mining Drone Beta Test Program"
      Description: "Participate in the Beta Program of brand new mining Drones!"
```
No need to define some localization keys inside the data. My translation method then accepts an path to the string like: translate('Inventory.raw_iron.name') or translate('Inventory', element.get_name, 'name') I don't know if there is something similiar in C# / Unity but it 

> @koosemose: I wouldn't be opposed to a system that works like that, if it can be done in a performant way (having to parse a string like that with regularity might be bad, since a lot of this stuff is ran for UI updates, which means every frame). I would advise putting that forward in an issue of its own, but unless you think you can implement it, the chance of uptake is low

Well this is the topic - I certainly have not enough time to do it myself but as I think its important I created it, so whoever reads this - feel free to pick up the task and provide an PR.

In a quick google-search I found this: https://github.com/MoonGateLabs/i18n-unity-csharp. Not exactly what I meant and not updated for 2 years but covers some stuff you have to think about so a good starting point - might be even worth as base/fork for the _needed_ extension.

**Comment by koosemose** [comment]
I'm not sure exactly how the inventory comment has to do with localization, unless it's the localization keys that make it "too many", otherwise, data will continue to have however many keys are needed to encode the needed information.

Regarding localization, a few considerations for what our current localization system is capable of, of which functionality it should not lose without further discussion on why that functionality should be removed. TextLocalizer Component on scripts, such that a UI component can have its text set to a localization key, and it will automatically use the localized version, filling in data as needed. Downloading localization data from separate repo, this is for future considerations, so that new versions don't need to be released simply to update localization data. "Nested Localization", where if you localize the key "job_build_furniture" and pass an argument of "furn_smelter" it will parse the localized string of the first "Building {0}" to "Building Smelter", this of course allows vastly more simple localization that refers to specific objects, otherwise it would need to be handled in place every time. 

In theory, this wouldn't be far different from a system I suggested a while back for autogenerating the localization keys for prototypes, where it would take the prototype type as a prefix (e.g. "furniture" or "furn"), add the type of the specific object (e.g. "smelter"), and finally the specific localization detail (e.g. "name" or "description"), though since in the case of prototypes it's not clear to me how we would clearly define what localization types are available, other than having to dig through code to see what is available (compared to now where you can simply look at the prototype definitions to see what localization keys are used. This is a problem that would need to be solved (preferably other than simply a list somewhere of "here's what localization keys are available for each type of prototype").

The repo you linked doesn't seem vastly different from our current localization system, and doesn't address how something like keys for prototypes would be defined. The only notable advantage over our localization system is having variant text for different numbers.
